globalThis.APP_CONFIG = {
  API_BASE_URL: globalThis.APP_CONFIG?.API_BASE_URL ?? '',
  SUPABASE_URL: globalThis.APP_CONFIG?.SUPABASE_URL ?? '',
  SUPABASE_PUBLISHABLE_KEY: globalThis.APP_CONFIG?.SUPABASE_PUBLISHABLE_KEY ?? globalThis.APP_CONFIG?.SUPABASE_ANON_KEY ?? '',
  SUPABASE_ANON_KEY: globalThis.APP_CONFIG?.SUPABASE_ANON_KEY ?? globalThis.APP_CONFIG?.SUPABASE_PUBLISHABLE_KEY ?? '',
  ...globalThis.APP_CONFIG
};